version: "3.9"

services:
  backend:
    build:
      context: ./backend   # ✅ must be a mapping
    ports:
      - "8010:8010"
    env_file:
      - .env               # ✅ must be a list
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend  # ✅ must be a mapping
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloud_costs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:  # ✅ makes sure db is ready before backend starts
      test: ["CMD-SHELL", "pg_isready -U postgres -d cloud_costs"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
