services:
  # Backend (FastAPI)
  - type: web
    name: cloud-cost-optimizer-backend
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SQLMODEL_DATABASE_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: CORS_ORIGINS
        sync: false

  # Frontend (React static site)
  - type: web
    name: cloud-cost-optimizer-frontend
    env: static
    plan: free
    region: singapore
    buildCommand: npm install && npm run build
    publishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        sync: false
